# Generated by Django 4.2 on 2025-02-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_content_alter_post_author_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(default=None, max_length=255, null=True),
        ),
    ]
