# Generated by Django 4.2 on 2025-02-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(default="content", max_length=255),
        ),
    ]
