name: Django

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker image
      run: docker compose up
    - name: testing
      run: docker compose exec backend sh -c "pytest ."
